### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ghost** [ce-real/prj-rev-bwfs-dasmoto#4]
Grade: Needs Improvement.

Good job throughout. Try and add more indentation to your code. In addition, add alt attributes to the text. As a further challenge, consider adding more images and text to the website. I think it is something you are ready for!

**Comment by ce-real** [comment]
Thank you so much for the feedback!  This project was a huge help toward getting started with learning HTML and CSS and was a great opportunity to put my skills into practice.
